services:
  frontend:
    build:
      context: ../Inventory-App-UI
    ports:
      - "3000:3000"
    networks:
      - app-network
    depends_on:
      - backend

  backend:
    build:
      context: .
    ports:
      - "8080:8080"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge